### ISSUE TITLE
Visual Studio 2019 is crashing consistently if you try to look at a callstack with ReusableTask

### ISSUE THREAD

**Issue by vlasenkoalexey** [alanmcgovern/ReusableTasks#6]
Reproduces for 1.0.6 and 1.0.7 on VS2019 and 2017.
I understand that it is actually Visual Studio issue, but the chance that MS fixes it is 0.
I hope that this is something that can be easily fixed in a library.

**Comment by alanmcgovern** [comment]
Which version of 2019 are you using? I had better success with 16.6, the current stable.

**Comment by vlasenkoalexey** [comment]
That's magic, updated VS to 16.6 today, and it is not crashing anymore on 1.0.7.

**Comment by alanmcgovern** [comment]
I figured if I hit enough crashers the traces showed up as a high hitting problem :) either it was fixed by accident, or that occurred!

It was very frustrating dealing with that issue for the last while :(
